name: settings
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  dbus: ^0.6.3
  duration: ^3.0.6
  filesize: ^2.0.1
  filesystem_picker:
    git:
      url: https://github.com/Feichtmeier/filesystem_picker
      path: package
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  gsettings: ^0.2.3
  intl: ^0.17.0
  linux_system_info: ^0.0.7
  mime: ^1.0.0
  bluez: ^0.7.4
  flex_color_picker: ^2.1.2
  nm: ^0.4.0
  open_file: ^3.2.1
  path_provider: ^2.0.5
  pdf: ^3.6.0
  provider: ^6.0.1
  rive: ^0.8.1
  safe_change_notifier: ^0.1.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  udisks: ^0.3.0
  upower:
    git:
      url: https://github.com/canonical/upower.dart
  yaru:
    git:
      url: https://github.com/ubuntu/yaru.dart
  yaru_icons: ^0.1.2
  yaru_widgets:
    git:
      url: https://github.com/ubuntu/yaru_widgets.dart
  flutter_svg: ^1.0.0
  flutter_spinbox: ^0.8.0
  http: ^0.13.4
  xml: ^5.3.1

dev_dependencies:
  build_runner: ^2.1.2

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mockingjay: ^0.2.0
  mockito: ^5.0.16

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/multitasking/active-screen-edges-panel-mode/
    - assets/images/multitasking/active-screen-edges-dock-mode/
    - assets/images/multitasking/hot-corner-panel-mode/
    - assets/images/multitasking/hot-corner-dock-mode/
    - assets/images/multitasking/workspaces-panel-mode/
    - assets/images/multitasking/workspaces-dock-mode/
    - assets/images/cursor/
    - assets/images/appearance/panel-mode/
    - assets/images/appearance/dock-mode/
    - assets/images/appearance/auto-hide-panel-mode/
    - assets/images/appearance/auto-hide-dock-mode/
    - assets/rive/
    - assets/pdf_assets/